---
title: Description of IsoFraPy
jupyter: python3
format:
  html:
    theme: dark
---

# 定式化
## レイリープロセスによる同位体分別

### レイリーの式

レイリープロセスにはWorden et al. (2007)の定式化を用いる。水蒸気は常に飽和状態にあると仮定し、気温 $T$ が $dT$ 低下するごとに水蒸気量 ($q$) とデルタ値 ($\delta = R - 1$) の変化を陽解法で求める。

$$
    \delta_{n+1} = \frac{\alpha_{eq} - 1}{q_n} dq + \delta_n
$$

ここで、$dq$ は $q_n$ から $q_{n+1}$ への変化として表せる。

$$
    dq = q_{n+1} - q_n
$$

### 飽和水蒸気圧

飽和水蒸気圧 ($e_s$) は、Sonntag (1990) の式を用いて求める。

$$
    e_s \ \text{ [hPa]}= \exp \left( \frac{a}{T} + b + cT + dT^2 + e \ln(T) \right) / 100
$$

各係数は **Table 1** に示す。このモデルでは、水と氷の飽和水蒸気圧を 0 °C で切り替える。

#### Table 1: 飽和水蒸気圧の係数 (Sonntag, 1990)

| Phase  | $a$        | $b$         | $c$           | $d$           | $e$          |
|--------|------------|-------------|---------------|---------------|--------------|
| Liquid | -6096.9385 | 21.2409642  | -2.711193e-2  | 1.673952e-5   | 2.433502     |
| Ice    | -6024.5282 | 29.32707    | 1.0613868e-2  | -1.3198825e-5 | -0.49382577  |


飽和水蒸気圧 ($e_s$) は飽和混合比 ($w_s$) に変換できる。

$$
    w_s = \epsilon \frac{e_s}{P}
$$

ここで、$\epsilon$ は水と空気の平均分子量の比、$P$ は標準気圧 (1013 hPa) である。
また、混合比 ($w$) は比湿 ($q$) に変換できる。

$$
    q = \frac{q}{1 + w}
$$

### 平衡分別係数

水同位体の平衡分別係数 ($\alpha_{eq}$) は、Majoube (1971a; 1971b) の経験式を用いる。

$$
    \alpha_{eq,vl} = \exp \left( \frac{a_1}{T^2} + \frac{a_2}{T} + a_3 \right) 
$$

$$
    \alpha_{eq,vi} = \exp \left( \frac{a_1}{T^{b}} + a_2 \right) 
$$

各係数は **Table 2** に示す。不連続を防ぐため、$-20$–$0$ °C では $\alpha_{eq,vi}$ と $\alpha_{eq,vl}$ を線形内挿する。

#### Table 2: 平衡分別係数の係数 (Majoube, 1971)

| Process                                   | $a_1$   | $a_2$     | $a_3$       | $b$   |
|-------------------------------------------|---------|-----------|-------------|-------|
| $\mathsf{H_2^{18}O}$ (vapor $\to$ liquid) | 1137    | -0.4156   | -0.002067   |       |
| $\mathsf{HDO}$ (vapor $\to$ liquid)       | 24844   | -76.248   | 0.052612    |       |
| $\mathsf{H_2^{18}O}$ (vapor $\to$ ice)    | 11.839  | -0.028224 |             | 1     |
| $\mathsf{HDO}$ (vapor $\to$ ice)          | 16289   | -0.0945   |             | 2     |

## 海面からの蒸発時に生じる同位体分別

海面からの蒸発に伴う同位体分別は、Merlivat and Jouzel (1979) の定式化を用いる。

$$
    R_E = \alpha_{kin,evap} \frac{R_{sea} / \alpha_{eq} - h R_a}{1 - h}
$$

ここで、$R_E$ は蒸発した水の同位体比、$h$ は実効相対湿度で、

$$
    h = h_a \frac{w_{sat,a}}{w_{sat,sea}}
$$

動的分別係数 ($\alpha_{kin,evap}$) は以下のように求める。

$$
    \alpha_{kin,evap} = 
        \begin{cases} 
            1 - a       \quad& (u <   7 \ \text{[m/s]}) \\
            1 - b u + c \quad& (u \ge 7 \ \text{[m/s]})
        \end{cases}
$$              

本モデルでは、$u<7$ の場合の $\alpha_{kin,evap}$ を使用する。

#### Table 3: 動的分別係数の係数 (Merilivat, 1978)
| Process               | $a$     | $b$       | $c$       |
|-----------------------|---------|-----------|-----------|
| $\mathsf{H_2^{18}O}$  | 0.006   | 0.000285  | 0.00082   |
| $\mathsf{HDO}$        | 0.00528 | 0.0002508 | 0.0007216 |


## 低温での水蒸気が過飽和になった時に生じる同位体分別

$-20$ °C 以下での氷晶形成時の同位体分別は、Jouzel and Merlivat (1984) に従う。

$$
    \alpha_{eff} = \alpha_{kin,supersat} \cdot \alpha_{eq}
$$

動的分別係数 ($\alpha_{kin,supersat}$) は以下で表される。

$$
    \alpha_{kin,supersat} = \frac{S}{\alpha_{eq} (D / D') (S - 1) + 1}
$$

$S$ は氷に対する過飽和度で、

$$
    S = 
        \begin{cases}
            1 \quad& (T \ge -20 \ \text{[°C]}) \\
            1 - 0.003 T \quad& (T < -20 \ \text{[°C]})
        \end{cases}
$$

$-20$–$0$ °C の間では、Ciais and Jouzel (1994) に従い分別係数を線形内挿する。

## ポストプロセス：最終地点における降雪からの昇華

最終地点における降雪量 ($Sn$) は、地表付近の相対湿度に基づいたパラメタリゼーションによって表現する。具体的には、降雪が全て昇華した際に地表付近（気温$T_{surf}$, 水蒸気量$q_{surf}$）の相対湿度 ($h_{surf}$) を $dh$ だけ増加させるような量の降雪が上空で生じると仮定する。

$$
    Sn = q_{surf} \frac{dh}{h_{surf}}
$$

この時、雪の同位体比は、最終地点における上空の水蒸気の同位体比から求められる。

$$
    R_{Sn} = (R_{v,final} + 1) \alpha_{final} - 1
$$

$Sn$のうち、割合$f$が昇華により地表付近の大気に戻されるとすると、その量 ($q_{sub}$) は、

$$
    q_{sub} = Sn \cdot f
$$

このとき、地表付近の水蒸気量は、次のように更新される。

$$
    q_{surf, updated} = q_{surf} + q_{sub}
$$

また、地表付近の水蒸気の同位体比は、次のように更新される。

$$
    R_{surf, updated} = \frac{q_{surf} R_{surf} + q_{sub} R_{sub}}{q_{surf, updated}}
$$

# 全体のフロー

